[package]
name = "PIPE-100-b-1"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom="6.0"
serde={version="1",features=["derive"]}
serde_json="1"
slab = "0.4.3"
slab_tree = "0.3.2"
